akademik/urls.py
from django.urls import path
from . import views, views_c, views_t

# Uwaga: Niektóre ścieżki są wspólne!
urlpatterns = [
    # Ścieżki Użytkownika:
    path('panel_akademika', views.staffpanel_h, name='staffpanel_h'),
    path('panel_uzytkownika', views.userpanel, name='userpanel'),
    path('twoje_dane', views.showmydata, name='userdatapersonal'),
    path('aplikacja_ds', views.dormapply, name='dsapply'),
    # Ścieżki Rady Studentów:
    path('panel_rady', views_c.staffpanel_c, name='staffpanel_c'),
    path('kreator_akcji', views_c.makemeparty, name='makemeparty'),
    path('akcje_kwaterunkowe', views_c.allparties, name='allparties'),
    path('edytuj_akcje', views_c.changemeparty, name='changemeparty'),
    path('wnioski_o_akademik', views_c.allapplied, name='allapplied'),
    path('szukaj_uzytkownikow', views_c.allusers, name='allusers'),
    path(
     'edycja_uzytkownika/<int:user_id>', views_c.changeuser, name='changeuser'
     ),
    # Ścieżki Tłumacza:
    path('panel_tlumacza', views_t.translatorpanel, name='translatorpanel'),
    path(
     'ustaw_jezyk', views_t.setmylanguage, name='setmylanguage'
     ),
    path(
     'tlumacz_element', views_t.elementstranslate, name='elementstranslate'
     ),
    path(
     'tlumacz_liste', views_t.menustranslate, name='menustranslate'
     ),
]

esks/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),  # Potem wywalimy admina gdzie indziej...
    path('', include('strona.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('strona/', include('strona.urls')),
    path('rekruter/', include('rekruter.urls')),
    path('akademik/', include('akademik.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

akademik/models.py
from django.db import models
from esks.settings import AUTH_USER_MODEL


# W tej klasie będą elementy wspólne dla wszystkich paneli.
class PortalBaseItem(models.Model):
    PORTAL_CHOICES = [
        ('1', 'User'),
        ('2', 'Council'),
        ('3', 'Hotel'),
        ('4', 'Translator'), ]
    portal = models.CharField(
     max_length=1, unique=True, choices=PORTAL_CHOICES)
    title = models.CharField(max_length=200)
    descr = models.CharField(max_length=400)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['portal']


# To zestaw klas tłumaczeniowych dla panelu Akademika.
class HotelMenuItem(models.Model):
    title = models.CharField(max_length=200)
    position = models.IntegerField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['position']


class HotelLinkItem(models.Model):
    title = models.CharField(max_length=200)
    menu = models.IntegerField()
    position = models.IntegerField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['menu', 'position']


# To zestaw klas tłumaczeniowych dla panelu Rady
class CouncilMenuItem(models.Model):
    title = models.CharField(max_length=200)
    position = models.IntegerField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['position']


class CouncilLinkItem(models.Model):
    title = models.CharField(max_length=200)
    menu = models.IntegerField()
    position = models.IntegerField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['menu', 'position']


# To zestaw klas tłumaczeniowych dla panelu Tłumacza
class TranslatorMenuItem(models.Model):
    title = models.CharField(max_length=200)
    position = models.IntegerField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['position']


class TranslatorLinkItem(models.Model):
    title = models.CharField(max_length=200)
    menu = models.IntegerField()
    position = models.IntegerField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['menu', 'position']


# To zestaw klas tłumaczeniowych dla panelu Użytkownika
class UserMenuItem(models.Model):
    title = models.CharField(max_length=200)
    position = models.IntegerField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['position']


class UserLinkItem(models.Model):
    title = models.CharField(max_length=200)
    menu = models.IntegerField()
    position = models.IntegerField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['menu', 'position']


# Ta klasa tworzy i porządkuje akcje kwaterunkowe
# Dodaje też ogłoszenie w wielu językach.
class HousingParty(models.Model):
    title = models.CharField(blank=True, max_length=200)
    quarter = models.IntegerField()
    date_start = models.DateTimeField(blank=True, null=True)
    date_end = models.DateTimeField(blank=True, null=True)
    comment = models.TextField(blank=True)
    announcement = models.TextField(blank=True)
    userdata1 = models.BooleanField(default=False)
    sh_preferences = models.BooleanField(default=False)
    userdata2 = models.BooleanField(default=False)
    formmap = models.BooleanField(default=False)
    faculty_data = models.BooleanField(default=False)
    extra_info = models.BooleanField(default=False)
    agreements1 = models.BooleanField(default=False)
    agreements2 = models.BooleanField(default=False)
    agreements3 = models.BooleanField(default=False)
    owner = models.ForeignKey(
     AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['date_start', 'date_end', 'quarter']


# Klasa tłumaczeniowa związana z akcjami kwaterunkowymi
class HousingPartyItems(models.Model):
    party_title = models.CharField(blank=True, max_length=200)
    choose_party = models.CharField(blank=True, max_length=200)
    time_start = models.CharField(blank=True, max_length=200)
    time_end = models.CharField(blank=True, max_length=200)
    comment = models.CharField(blank=True, max_length=200)
    announce = models.CharField(blank=True, max_length=200)
    tick_form = models.CharField(blank=True, max_length=200)
    p_from = models.CharField(blank=True, max_length=200)
    p_to = models.CharField(blank=True, max_length=200)
    changeme = models.CharField(blank=True, max_length=200)
    all_parties = models.CharField(blank=True, max_length=200)
    active_parties = models.CharField(blank=True, max_length=200)
    past_parties = models.CharField(blank=True, max_length=200)
    future_parties = models.CharField(blank=True, max_length=200)
    new_party_view = models.CharField(blank=True, max_length=200)
    owner = models.CharField(blank=True, max_length=200)
    userinfo = models.CharField(blank=True, max_length=250)
    housing_party = models.CharField(blank=True, max_length=200)
    change_and_apply = models.CharField(blank=True, max_length=200)


# Klasa tłumaczeniowa dla elementów rozwijanego menu sortowania wniosków.
class ApplicationListItems(models.Model):
    realname = models.CharField(max_length=200)
    basename = models.CharField(max_length=200)
    position = models.IntegerField()

    def __str__(self):
        return self.realname

    class Meta:
        ordering = ['position']


# Klasa tłumaczeniowa dla elementów rozwijanego menu sortowania uzytkowników.
class UserListItems(models.Model):
    realname = models.CharField(max_length=200)
    basename = models.CharField(max_length=200)
    position = models.IntegerField()

    def __str__(self):
        return self.realname

    class Meta:
        ordering = ['position']


# Klasa tłumaczeniowa dla elementów strony, które będą widoczne
# tylko w panelach administracyjnych. Tylko charfields.
class AdminTextTools(models.Model):
    sortme = models.CharField(max_length=200)
    ascending = models.CharField(max_length=200)
    descending = models.CharField(max_length=200)
    non_assigned = models.CharField(max_length=200)
    change_forbidden = models.CharField(max_length=200)
    council_member = models.CharField(max_length=200)
    is_translator = models.CharField(max_length=200)
    mypermissions = models.CharField(max_length=200)
    searchme = models.CharField(max_length=200)

akademik/views.py
from django.shortcuts import (render, redirect, get_object_or_404 as G404)
from strona.models import (Pageitem as P, PageSkin as S)
from esks.settings import LANGUAGES as L
from esks.special.classes import PortalLoad, PageElement, PartyMaster
from .models import (
 PortalBaseItem as Pbi, UserMenuItem as Umi, UserLinkItem as Uli,
 HotelMenuItem as Hmi, HotelLinkItem as Hli, HousingParty as HParty)
from rekruter.models import (
 StudentHouse as Sh, IfRoomChange as Ifr, TimePeriod as Tper,
 StudyFaculty as Stf, StudyDegree as Std, SpouseCohabitant as Sch,
 SpecialCase as Scs, User, FormItems, QuarterClassB)
from esks.special.decorators import hotel_staff_only
from rekruter.forms import IniForm, ApplicationForm
import datetime
import pytz


# Panel Obsługi Akademików
@hotel_staff_only(login_url='logger')
def staffpanel_h(request):
    # zdefiniuj dodatkowe konteksty tutaj.
    pl = PortalLoad(P, L, Pbi, 2, Hmi, Hli)
    context_lazy = pl.lazy_context(skins=S)
    template = 'panels/hotel/panel_akademika.html'
    return render(request, template, context_lazy)


# Panel użytkownika.
# Jeśli nie masz jeszcze przydzielonej kwatery,
# przekieruje Cię najpierw do przydziału.
def userpanel(request):
    quarter = request.user.quarter
    if quarter == '':
        return redirect('initial')
    else:
        # zdefiniuj dodatkowe konteksty tutaj.
        pl = PortalLoad(P, L, Pbi, 0, Umi, Uli, )
        context_lazy = pl.lazy_context(skins=S)
    template = 'panels/user/panel_uzytkownika.html'
    return render(request, template, context_lazy)


# Funkcja pokazuje dane użytkownika i pozwala zmienić akcję kwaterunkową.
def showmydata(request):
    userdata = User.objects.get(
     id=request.user.id)
    if request.method == 'POST':
        form = IniForm(request.POST, instance=userdata)
        if form.is_valid():
            form.save()
            return redirect('userdatapersonal')
    else:
        pe_fi = PageElement(FormItems)
        peqc = PageElement(QuarterClassB)
        form = IniForm()
        quarter = userdata.__dict__['quarter']
        myquarter = peqc.list_specific(int(quarter)-1)
        quarterlist = peqc.listed
        context = {
         'formitem': pe_fi.baseattrs,
         'form': form,
         'setter': myquarter,
         'setlist': quarterlist,
         'udata': userdata,
         }
        # zdefiniuj dodatkowe konteksty tutaj.
        pl = PortalLoad(P, L, Pbi, 0, Umi, Uli, )
        context_lazy = pl.lazy_context(skins=S, context=context)
        template = 'panels/user/mydata.html'
        return render(request, template, context_lazy)


# Funkcja sprawdza czy akcja użytkownika jest tą właściwą i jeśli nie,
# daje mu inne do wyboru. Rownież w razie jakby ktoś dał ciała i zdefiniował
# dwie akcje kwaterunkowe tego samego typu, to funkcja zwróci Id tylko 1.
def party_switch(request):
    y = PartyMaster(HParty, pytz, datetime)
    z = y.dict_active_id_quarter()
    print(z)
    quarter = request.user.quarter
    if quarter in z.values():
        # Ten kawałek uzyskuje pierwszy klucz z wartości słownika...
        a = list(z.keys())[list(z.values()).index(quarter)]
        print('nowy formularz...')
        request.session['partyformid'] = a
        return 0
    else:
        print('przekierowuję...')
        return 1


# Jeden widok dla wszystkich formularzy aplikacyjnych.
def dormapply(request):
    userdata = User.objects.get(
     id=request.user.id)
    service = True
    if request.method == 'POST':
        form = ApplicationForm(request.POST)
        if form.is_valid():
            form.save(userdata, request=request)
            return redirect('userpanel')
    else:
        redir = party_switch(request)
        if redir == 1:
            return redirect('allparties')  # Gdzie przekierować?
        else:
            pe_fi = PageElement(FormItems)
            form = ApplicationForm()
            sh = PageElement(Sh)
            ifr = PageElement(Ifr)
            tper = PageElement(Tper)
            stf = PageElement(Stf)
            std = PageElement(Std)
            sch = PageElement(Sch)
            scs = PageElement(Scs)
            hp = PageElement(HParty)
            puzzle = hp.by_id(G404=G404, id=request.session['partyformid'])
            context = {
             'udata': userdata,
             'formitem': pe_fi.baseattrs,
             'form': form,
             'houselist': sh.list_shorter(cut_fr=1),
             'staylist': ifr.list_shorter(cut_fr=1),
             'periodlist': tper.list_shorter(cut_fr=1),
             'facultylist': stf.list_shorter(cut_fr=1),
             'degreelist': std.list_shorter(cut_fr=1),
             'spouselist': sch.list_shorter(cut_fr=1),
             'scaselist': scs.list_shorter(cut_fr=1),
             'service': service,
             'puzzle': puzzle
             }
            pl = PortalLoad(P, L, Pbi, 0, Umi, Uli, )
            context_lazy = pl.lazy_context(skins=S, context=context)
            template = 'forms/dormapply.html'
            return render(request, template, context_lazy)

akademik/templates/panels/user/dormapply.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
<title>{{ link.3 }}</title>
{% endblock %}

{% block css %}
{% endblock %}
{% block css2 %}
{% endblock %}

<!--Zwraca oryginalną kompozycję menu z bazy. Potem podstawiasz zmienne,-->
{% block aside %}
 {{ block.super }}
{% endblock aside %}

{% block menu %}
 {% include 'menus/user_menus.html' %} <!-- Menu z opcjami użytkownika -->
{% endblock menu %}

{% block body %}
 {% include 'panels/user/userdata1.html' %} <!-- Podstawowe dane Usera -->
 {% include 'panels/user/sh_preferences.html' %} <!-- Preferencje Usera -->
 {% include 'panels/user/userdata2.html' %} <!-- Rozszerzone dane Usera -->
 {% include 'panels/user/formmap.html' %} <!-- Mapka do zaznaczania -->
 {% include 'panels/user/faculty_data.html' %} <!-- Dane wydziału -->


  <form enctype="multipart/form-data" method="post"> <!-- Do wysyłania plików -->
    {% csrf_token %}


    <input id="send" class="button" name="subbutton" type="submit" value="{{ formitem.sendme }}">
  </form>
{% endblock body %}


{% block scripts %}
 <!-- Napisz od nowa i zmień ten skrpt, żeby wypełniał pola ukryte.-->
<script src="{% static "quarterchange.js" %}"></script>
{% endblock %}

{% block scripts2 %}
{% endblock %}

akademik/templates/panels/user/faculty_data.html
<!-- Dane toku studiów - tylko jeśli student. Domyślnie: nie dotyczy. -->
<h4> {{ formitem.pref_as_stud }} </h4>
<p> {{ formitem.faculty }}
    <select id="faculty">
             <option value ="None" disabled>{{ formitem.list_select }}:</option>
           {% for item in facultylist %}
              <option value ="{{ forloop.counter }}">{{ item }}</option>
           {% endfor %}
    </select>
</p>
<p> {{ formitem.degree }}
    <select id="degree">
             <option value ="None" disabled>{{ formitem.list_select }}:</option>
           {% for item in degreelist %}
              <option value ="{{ forloop.counter }}">{{ item }}</option>
           {% endfor %}
    </select>
</p>
<p> {{ formitem.deangroup }} {{ form.deangroup }} </p>
<p> {{ formitem.semester }}
  <select id="semester">
           <option value ="None" disabled>{{ formitem.list_select }}:</option>
           <option value ="0">-</option>
         {% for item in "1"|rjust:"12"  %}
            <option value ="{{ forloop.counter }}">{{ forloop.counter }}</option>
         {% endfor %}
  </select>
</p>
{% if udata.album %}
<p> {{ formitem.album }} {{ udata.album }}</p>
{% endif %}
<p>

akademik/templates/panels/user/mydata.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
<title>{{ link.6 }}</title>
{% endblock %}

{% block css %}
{% endblock %}
{% block css2 %}
{% endblock %}

<!--Zwraca oryginalną kompozycję menu z bazy. Potem podstawiasz zmienne,-->
{% block aside %}
 {{ block.super }}
{% endblock aside %}

{% block menu %}
{% if service2 %}
 {% include 'menus/council_menus.html' %} <!-- Menu z opcjami użytkownika -->
{% else %}
 {% include 'menus/user_menus.html' %}
{% endif %}
{% endblock menu %}

{% block body %}
 {% include 'forms/elements/userdata1.html' %} <!-- Podstawowe dane Usera -->
  <p class="maintitle">{{ formitem.action }}</p>
  <div class="alert alert-secondary alert-dismissible">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <p><b class="alerto"> {{ formitem.assigned_to }}</b>: {{ setter }} <b class="alerto"> lub {{ formitem.change_man }}:</b></p>
  </div>
  <div class="mydatass">
    <br>
  <form name="QuarterForm" method="post" class="form form-inline formula3">
        <select id="Quarterselector" name="Quarter" class="form form-inline formula3">
          <option value ="None" disabled>{{ formitem.list_select }}:</option>
        {% for item in setlist %}
           <option value ="{{ forloop.counter }}">{{ item }}</option>
        {% endfor %}
        </select>
      {% csrf_token %}
      <input type="hidden" name="quarter" id="id_quarter">
      <div class="sort4">
      <button  id="send" class="btn btn-dark btn-sm" name="subbutton" type="submit" value="{{ formitem.choose }}">WYBIERZ</button>
      </div>
  </form>

  {% if service2 %}
   <br>

<p><b class="czeko2">{{ attools.mypermissions }}: </b></p>
  {% else %}
   <p><b class="czeko">{{ formitem.or_if }}</b></p>
   <p><a href="{% url 'initial' %}" class="btn">{{ formitem.assign_again }}</a></p> <!-- Tutaj ma być button -->
  {% endif %}
<!-- Tutaj jest opcja, żeby dodać userowi specjalne uprawnienia widoczna tylko dla ziomków z lvl 2+ -->
<!-- Zmienić można tylko osobom do lvl 1 -->
{% if user.role_council > 2 and udata.role_council < 3 %}
  <form name="AccessForm" method="post" class="form form-inline">

        <!-- Checkbox pokazuje i zmienia stan uprawnień osoby do bycia w radzie z 0 na 1 i na odwrót -->
        <p class="czeko">{{ attools.council_member }}  {{ form2.role_council }}</p>
        <!-- Checkbox pokazuje i zmienia stan uprawnień osoby do bycia tłumaczem z 0 na 1 i na odwrót -->
        <p class="czeko">{{ attools.is_translator }}  {{ form2.is_translator }}</p>

      {% csrf_token %}

    <div class="sort4">
      <br>
      <br>
    <button  id="send2" class="btn btn-dark btn-sm btn-block" name="power" type="submit" value="{{ formitem.sendme }}">WYŚLIJ</button>
    </div>
  </form>
  <br>
  </div>
{% elif  user.role_council > 2 and udata.role_council > 2 %}
  <p>{{ attools.change_forbidden }}</p>
{% endif %}

{% endblock body %}


{% block scripts %}
<script src="{% static "quarterchange.js" %}"></script>
{% endblock %}

{% block scripts2 %}
{% endblock %}

akademik/templates/panels/user/panel_uzytkownika.html
<!-- Goły panel użytkownika. Na początku nic się nie wyświetla. A mogłoby -->
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
<title>Panel Użytkownika</title>
{% endblock %}

{% block css %}
{% endblock %}
{% block css2 %}
{% endblock %}

<!--Zwraca oryginalną kompozycję menu z bazy. Potem podstawiasz zmienne,-->
{% block aside %}
 {{ block.super }}
{% endblock aside %}

{% block menu %}
 {% include 'menus/user_menus.html' %} <!-- Menu z opcjami użytkownika -->
{% endblock menu %}

{% block body %}
 <!-- Tu mają się wyświetlać dane z różnych opcji po kliknięciu -->
{% endblock body %}


{% block scripts %}
{% endblock %}
{% block scripts2 %}
{% endblock %}