akademik/urls.py
from django.urls import path
from . import views, views_c, views_t

# Uwaga: Niektóre ścieżki są wspólne!
urlpatterns = [
    # Ścieżki Użytkownika:
    path('panel_akademika', views.staffpanel_h, name='staffpanel_h'),
    path('panel_uzytkownika', views.userpanel, name='userpanel'),
    path('twoje_dane', views.showmydata, name='userdatapersonal'),
    path('aplikacja_ds', views.dormapply, name='dsapply'),
    # Ścieżki Rady Studentów:
    path('panel_rady', views_c.staffpanel_c, name='staffpanel_c'),
    path('kreator_akcji', views_c.makemeparty, name='makemeparty'),
    path('akcje_kwaterunkowe', views_c.allparties, name='allparties'),
    path('edytuj_akcje', views_c.changemeparty, name='changemeparty'),
    path('wnioski_o_akademik', views_c.allapplied, name='allapplied'),
    path('szukaj_uzytkownikow', views_c.allusers, name='allusers'),
    path(
     'edycja_uzytkownika/<int:user_id>', views_c.changeuser, name='changeuser'
     ),
    # Ścieżki Tłumacza:
    path('panel_tlumacza', views_t.translatorpanel, name='translatorpanel'),
    path(
     'ustaw_jezyk', views_t.setmylanguage, name='setmylanguage'
     ),
    path(
     'tlumacz_element', views_t.elementstranslate, name='elementstranslate'
     ),
    path(
     'tlumacz_liste', views_t.menustranslate, name='menustranslate'
     ),
]

esks/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),  # Potem wywalimy admina gdzie indziej...
    path('', include('strona.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('strona/', include('strona.urls')),
    path('rekruter/', include('rekruter.urls')),
    path('akademik/', include('akademik.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rekruter/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from rekruter.models import User, ApplicationFormFields
from akademik.models import HousingParty as HParty
from esks.special.classes import checkifnull as cn
import datetime


class ExtendedCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=75)
    gender = forms.CharField(widget=forms.HiddenInput(), required=False)
    citizenship = forms.CharField(max_length=30)
    dowod = forms.CharField(max_length=20, required=False)
    passport = forms.CharField(max_length=20, required=False)
    telephone = forms.CharField(max_length=30)
    street = forms.CharField(max_length=30)
    building_no = forms.CharField(max_length=15)
    local_no = forms.CharField(max_length=10, required=False)
    postcode = forms.CharField(max_length=7)
    city = forms.CharField(max_length=25)
    album = forms.CharField(max_length=25, required=False)

    class Meta:
        model = User
        fields = (
            'email',
            'password1',
            'password2',
            'first_name',
            'last_name',
            'gender',
            'citizenship',
            'dowod',
            'passport',
            'telephone',
            'street',
            'building_no',
            'local_no',
            'postcode',
            'city',
            'album',
        )

    def save(self, commit=True):
        user = super(ExtendedCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.gender = int(self.cleaned_data["gender"])
        user.citizenship = self.cleaned_data["citizenship"]
        user.dowod = self.cleaned_data["dowod"]
        user.passport = self.cleaned_data["passport"]
        user.telephone = self.cleaned_data["telephone"]
        user.street = self.cleaned_data["street"]
        user.building_no = self.cleaned_data["building_no"]
        user.local_no = self.cleaned_data["local_no"]
        user.postcode = self.cleaned_data["postcode"]
        user.city = self.cleaned_data["city"]
        user.city = self.cleaned_data["album"]

        if commit:
            user.save()
        return user


# Zmienia akcję kwaterunkową.
class IniForm(forms.ModelForm):
    quarter = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = User
        fields = ('quarter', )

    def save(self, commit=True):
        user = super(IniForm, self).save(commit=False)
        user.quarter = self.cleaned_data["quarter"]
        if commit:
            user.save()
        return user


# Zmienia podstawowe uprawnienia dla rady studentów.
class PowerForm(forms.ModelForm):
    role_council = forms.BooleanField(required=False)
    is_translator = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ('is_translator', )

    def save(self, role, commit=True):
        user = super(PowerForm, self).save(commit=False)
        user.is_translator = self.cleaned_data["is_translator"]
        user.role_council = role
        if commit:
            user.save()
        return user


# Nadaje podstawowe uprawnienia Userowi stworzonemu z poziomu panelu admina.
# Ogólnie nie powinno być tego w kodzie, ale dzięki temu unikniemy problemów.
class BasicPowerForm(forms.ModelForm):
    # role_council = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ('role_council', )

    def save(self, role, commit=True):
        user = super(BasicPowerForm, self).save(commit=False)
        user.role_council = role
        if commit:
            user.save()
        return user


# Zmienia akcję kwaterunkową.
class LangForm(forms.ModelForm):
    language = forms.CharField(max_length=2, required=False)

    class Meta:
        model = User
        fields = ()

    def save(self, lang, commit=True):
        user = super(LangForm, self).save(commit=False)
        user.language = lang
        if commit:
            user.save()
        return user


# Formularz to tworzenia i modyfikowania podań o akademik. UWAGA!
# Rośnie Ci złożoność cyklomatyczna! - najlepiej zrób dwa formularze.
# Jeden do tworzenia a drugi do modyfikacji.
class ApplicationForm(forms.ModelForm):
    sh_choice1 = forms.CharField(widget=forms.HiddenInput(), required=False)
    sh_choice2 = forms.CharField(widget=forms.HiddenInput(), required=False)
    sh_choice3 = forms.CharField(widget=forms.HiddenInput(), required=False)
    if_room_change = forms.CharField(widget=forms.HiddenInput(), required=False)
    duration = forms.CharField(widget=forms.HiddenInput(), required=False)
    location = forms.CharField(widget=forms.HiddenInput(), required=False)
    faculty = forms.CharField(widget=forms.HiddenInput(), required=False)
    degree = forms.CharField(widget=forms.HiddenInput(), required=False)
    deangroup = forms.CharField(max_length=30, required=False)
    semester = forms.CharField(widget=forms.HiddenInput(), required=False)
    spouse_cohabitant = forms.CharField(widget=forms.HiddenInput(), required=False)
    special_case_docs = forms.CharField(widget=forms.HiddenInput(), required=False)
    international_placement = forms.CharField(widget=forms.HiddenInput(), required=False)
    mailinglist = forms.CharField(widget=forms.HiddenInput(), required=False)
    dataprocessing = forms.CharField(widget=forms.HiddenInput(), required=False)
    # attachment = forms.FileField(max_length=250, allow_empty_file=True)

    class Meta:
        model = ApplicationFormFields
        fields = (

        )

    def save(self, uid, commit=True, **kwargs):
        application = super(ApplicationForm, self).save(commit=False)
        application.owner = uid
        application.sh_choice1 = cn(self.cleaned_data["sh_choice1"], 0)
        application.sh_choice2 = cn(self.cleaned_data["sh_choice2"], 0)
        application.sh_choice3 = cn(self.cleaned_data["sh_choice3"], 0)
        application.if_room_change = cn(self.cleaned_data["if_room_change"], 0)
        application.duration = cn(self.cleaned_data["duration"], 0)
        application.location = self.cleaned_data["location"]
        application.faculty = cn(self.cleaned_data["faculty"], 0)
        application.degree = cn(self.cleaned_data["degree"], 0)
        application.deangroup = self.cleaned_data["deangroup"]
        application.semester = cn(self.cleaned_data["semester"], 0)
        application.spouse_cohabitant = cn(self.cleaned_data["spouse_cohabitant"], 0)
        application.special_case_docs = cn(self.cleaned_data["special_case_docs"], 0)
        application.international_placement = self.cleaned_data["international_placement"]
        application.mailinglist = self.cleaned_data["mailinglist"]
        application.dataprocessing = self.cleaned_data["dataprocessing"]
        # application.attachment = self.cleaned_data["attachment"]
        if application.timeapplied is None:
            application.timeapplied = datetime.datetime.now()
        if application.status is None:
            application.status = 0
        if application.quarter is None:
            request = kwargs['request']
            application.quarter = request.user.quarter
        if commit:
            application.save()
        return application


class PartyForm(forms.ModelForm):
    title_pl = forms.CharField(max_length=200)
    title_en = forms.CharField(max_length=200)
    quarter = forms.CharField(widget=forms.HiddenInput())
    date_start = forms.DateTimeField(input_formats=['%d.%m.%Y %H:%M:%S'])
    date_end = forms.DateTimeField(input_formats=['%d.%m.%Y %H:%M:%S'])
    comment_pl = forms.CharField(widget=forms.Textarea, required=False)
    comment_en = forms.CharField(widget=forms.Textarea, required=False)
    announcement_pl = forms.CharField(widget=forms.Textarea, required=False)
    announcement_en = forms.CharField(widget=forms.Textarea, required=False)
    userdata1 = forms.BooleanField(required=False)
    sh_preferences = forms.BooleanField(required=False)
    userdata2 = forms.BooleanField(required=False)
    formmap = forms.BooleanField(required=False)
    faculty_data = forms.BooleanField(required=False)
    extra_info = forms.BooleanField(required=False)
    agreements1 = forms.BooleanField(required=False)
    # agreements2 = forms.BooleanField(required=False)
    # agreements3 = forms.BooleanField(required=False)

    class Meta:
        model = HParty
        fields = (
         'title_pl', 'title_en', 'quarter', 'date_start', 'date_end',
         'comment_pl', 'comment_en', 'announcement_pl', 'announcement_en',
         'userdata1',  'sh_preferences', 'userdata2',
         'formmap', 'faculty_data', 'extra_info', 'agreements1')

    def save(self, uid, commit=True):
        party = super(PartyForm, self).save(commit=False)
        party.owner = uid
        party.title_pl = self.cleaned_data["title_pl"]
        party.title_en = self.cleaned_data["title_en"]
        party.quarter = self.cleaned_data["quarter"]
        party.date_start = self.cleaned_data["date_start"]
        party.date_end = self.cleaned_data["date_end"]
        party.comment_pl = self.cleaned_data["comment_pl"]
        party.comment_en = self.cleaned_data["comment_en"]
        party.announcement_pl = self.cleaned_data["announcement_pl"]
        party.announcement_en = self.cleaned_data["announcement_en"]
        party.userdata1 = self.cleaned_data["userdata1"]
        party.sh_preferences = self.cleaned_data["sh_preferences"]
        party.userdata2 = self.cleaned_data["userdata2"]
        party.formmap = self.cleaned_data["formmap"]
        party.faculty_data = self.cleaned_data["faculty_data"]
        party.extra_info = self.cleaned_data["extra_info"]
        party.agreements1 = self.cleaned_data["agreements1"]

        if commit:

akademik/views.py
from django.shortcuts import (render, redirect, get_object_or_404 as G404)
from strona.models import (Pageitem as P, PageSkin as S)
from esks.settings import LANGUAGES as L
from esks.special.classes import PortalLoad, PageElement, PartyMaster
from .models import (
 PortalBaseItem as Pbi, UserMenuItem as Umi, UserLinkItem as Uli,
 HotelMenuItem as Hmi, HotelLinkItem as Hli, HousingParty as HParty)
from rekruter.models import (
 StudentHouse as Sh, IfRoomChange as Ifr, TimePeriod as Tper,
 StudyFaculty as Stf, StudyDegree as Std, SpouseCohabitant as Sch,
 SpecialCase as Scs, User, FormItems, QuarterClassB)
from esks.special.decorators import hotel_staff_only
from rekruter.forms import IniForm, ApplicationForm
import datetime
import pytz


# Panel Obsługi Akademików
@hotel_staff_only(login_url='logger')
def staffpanel_h(request):
    # zdefiniuj dodatkowe konteksty tutaj.
    pl = PortalLoad(P, L, Pbi, 2, Hmi, Hli)
    context_lazy = pl.lazy_context(skins=S)
    template = 'panels/hotel/panel_akademika.html'
    return render(request, template, context_lazy)


# Panel użytkownika.
# Jeśli nie masz jeszcze przydzielonej kwatery,
# przekieruje Cię najpierw do przydziału.
def userpanel(request):
    quarter = request.user.quarter
    if quarter == '':
        return redirect('initial')
    else:
        # zdefiniuj dodatkowe konteksty tutaj.
        pl = PortalLoad(P, L, Pbi, 0, Umi, Uli, )
        context_lazy = pl.lazy_context(skins=S)
    template = 'panels/user/panel_uzytkownika.html'
    return render(request, template, context_lazy)


# Funkcja pokazuje dane użytkownika i pozwala zmienić akcję kwaterunkową.
def showmydata(request):
    userdata = User.objects.get(
     id=request.user.id)
    if request.method == 'POST':
        form = IniForm(request.POST, instance=userdata)
        if form.is_valid():
            form.save()
            return redirect('userdatapersonal')
    else:
        pe_fi = PageElement(FormItems)
        peqc = PageElement(QuarterClassB)
        form = IniForm()
        quarter = userdata.__dict__['quarter']
        myquarter = peqc.list_specific(int(quarter)-1)
        quarterlist = peqc.listed
        context = {
         'formitem': pe_fi.baseattrs,
         'form': form,
         'setter': myquarter,
         'setlist': quarterlist,
         'udata': userdata,
         }
        # zdefiniuj dodatkowe konteksty tutaj.
        pl = PortalLoad(P, L, Pbi, 0, Umi, Uli, )
        context_lazy = pl.lazy_context(skins=S, context=context)
        template = 'panels/user/mydata.html'
        return render(request, template, context_lazy)


# Funkcja sprawdza czy akcja użytkownika jest tą właściwą i jeśli nie,
# daje mu inne do wyboru. Rownież w razie jakby ktoś dał ciała i zdefiniował
# dwie akcje kwaterunkowe tego samego typu, to funkcja zwróci Id tylko 1.
def party_switch(request):
    y = PartyMaster(HParty, pytz, datetime)
    z = y.dict_active_id_quarter()
    print(z)
    quarter = request.user.quarter
    if quarter in z.values():
        # Ten kawałek uzyskuje pierwszy klucz z wartości słownika...
        a = list(z.keys())[list(z.values()).index(quarter)]
        print('nowy formularz...')
        request.session['partyformid'] = a
        return 0
    else:
        print('przekierowuję...')
        return 1


# Jeden widok dla wszystkich formularzy aplikacyjnych.
def dormapply(request):
    userdata = User.objects.get(
     id=request.user.id)
    service = True
    if request.method == 'POST':
        form = ApplicationForm(request.POST)
        if form.is_valid():
            form.save(userdata, request=request)
            return redirect('userpanel')
    else:
        redir = party_switch(request)
        if redir == 1:
            return redirect('allparties')  # Gdzie przekierować?
        else:
            pe_fi = PageElement(FormItems)
            form = ApplicationForm()
            sh = PageElement(Sh)
            ifr = PageElement(Ifr)
            tper = PageElement(Tper)
            stf = PageElement(Stf)
            std = PageElement(Std)
            sch = PageElement(Sch)
            scs = PageElement(Scs)
            hp = PageElement(HParty)
            puzzle = hp.by_id(G404=G404, id=request.session['partyformid'])
            context = {
             'udata': userdata,
             'formitem': pe_fi.baseattrs,
             'form': form,
             'houselist': sh.list_shorter(cut_fr=1),
             'staylist': ifr.list_shorter(cut_fr=1),
             'periodlist': tper.list_shorter(cut_fr=1),
             'facultylist': stf.list_shorter(cut_fr=1),
             'degreelist': std.list_shorter(cut_fr=1),
             'spouselist': sch.list_shorter(cut_fr=1),
             'scaselist': scs.list_shorter(cut_fr=1),
             'service': service,
             'puzzle': puzzle
             }
            pl = PortalLoad(P, L, Pbi, 0, Umi, Uli, )
            context_lazy = pl.lazy_context(skins=S, context=context)
            template = 'forms/dormapply.html'
            return render(request, template, context_lazy)

akademik/templates/forms/elements/agreements.html
<!-- Zgody do celów demonstracyjnych. Potem do zmiany na bardziej modularne. -->
{% load staticfiles %}
<div class="card cardio">
<div class="maintitle">{{ formitem.statement }}</div>
<div class="card-body">
<p class="agree">
  <select {% if service %} required {% endif %}  id="international_placement" class="form-control form-control-sm">
             <option value ="None" disabled="disabled" selected="selected">{{ formitem.list_select }}:</option>
             <option value ="0">{{ formitem.disagree }}</option>
             <option value ="1">{{ formitem.agree }}</option>
    </select>
    {{ formitem.agree_international }}
</p>
<p class="agree">
  <input id="mailinglist" type="checkbox">
  {{ formitem.mail_join }}
</p>
<p class="agree">
  <input {% if service %} required {% endif %} id="dataprocessing" type="checkbox">
  {{ formitem.data_processing }}
</p>
</div>
</div>
<br>

<!--Ukryte pola formularza-->
{{ form.international_placement }}{{ form.mailinglist }}{{ form.dataprocessing }}
<!--Skrypt zapełniający pola-->
<script>
  $(document).ready(function()
  {
    $('#send').click(function()
   {
     formfill("international_placement", "id_international_placement")
     formcheckfill("mailinglist", "id_mailinglist")
     formcheckfill("dataprocessing", "id_dataprocessing")
  });
});
</script>

akademik/templates/forms/elements/extra_info.html
<!-- Dodatkowe dane: Czy chce mieszkać z małżonkiem i czy jest niepełnosprawny/a -->
<!-- Domyślnie: Nie składa -->
<div class="card cardio">
<div class="maintitle"> {{ formitem.additional_info }}</div>
<div class="card-body">
<p class="extras"> {{ formitem.spouse_cohabitant }}:
  <select {% if service %} required {% endif %} id="spouse_cohabitant" class="form-control">
             <option value ="None" disabled="disabled" selected="selected">{{ formitem.list_select }}:</option>
           {% for item in spouselist %}
              <option value ="{{ forloop.counter }}">{{ item }}</option>
           {% endfor %}
    </select>
</p>
<p class="extras"> {{ formitem.special_case_docs }}:
    <select {% if service %} required {% endif %} id="special_case_docs" class="form-control">
             <option value ="None" disabled="disabled" selected="selected">{{ formitem.list_select }}:</option>
           {% for item in scaselist %}
              <option value ="{{ forloop.counter }}">{{ item }}</option>
           {% endfor %}
    </select>
</p>
</div>
</div>

<br>

<!--Ukryte pola formularza-->
{{ form.spouse_cohabitant }}{{ form.special_case_docs }}
<!--Skrypt zapełniający pola-->
<script>
  $(document).ready(function()
  {
    $('#send').click(function()
   {
     formfill("spouse_cohabitant", "id_spouse_cohabitant")
     formfill("special_case_docs", "id_special_case_docs")
  });
});
</script>

akademik/templates/forms/elements/faculty_data.html
<!-- Dane toku studiów - tylko jeśli student. Domyślnie: nie dotyczy. -->
{% load staticfiles %}
<div class="card cardio">
<div class="maintitle"> {{ formitem.pref_as_stud }}: </div>
<div class="card-body">
<p class="pref2"> {{ formitem.faculty }}:
    <select {% if service %} required {% endif %} id="faculty" class="form-control form-control-sm">
             <option value ="None" disabled="disabled" selected="selected">{{ formitem.list_select }}:</option>
           {% for item in facultylist %}
              <option value ="{{ forloop.counter }}">{{ item }}</option>
           {% endfor %}
    </select>
</p>
<p class="pref2"> {{ formitem.degree }}:
    <select {% if service %} required {% endif %} id="degree" class="form-control form-control-sm">
             <option value ="None" disabled="disabled" selected="selected">{{ formitem.list_select }}:</option>
           {% for item in degreelist %}
              <option value ="{{ forloop.counter }}">{{ item }}</option>
           {% endfor %}
    </select>
</p>

<p class="dziek"><label for="id_deangroup">{{ formitem.deangroup }}: </label>
<input type="text" name="deangroup" maxlength="30" id="id_deangroup" class="form-control form-control-sm"> </p>

<p class="pref2"> {{ formitem.semester }}:
  <select {% if service %} required {% endif %} id="semester" class="form-control form-control-sm numb">
           <option value ="None" disabled="disabled" selected="selected">{{ formitem.list_select }}:</option>
           <option value ="0">-</option>
         {% for item in "1"|rjust:"12"  %}
            <option value ="{{ forloop.counter }}">{{ forloop.counter }}</option>
         {% endfor %}
  </select>
</p>
{% if udata.album %}
<p class="pref2"> {{ formitem.album }} {{ udata.album }}</p>
{% endif %}

</div>
</div>
<br>

<!--Ukryte pola formularza-->
{{ form.faculty }}{{ form.degree }}{{ form.semester }}
<!--Skrypt zapełniający pola-->
<script>
  $(document).ready(function()
  {
    $('#send').click(function()
   {
     formfill("faculty", "id_faculty")
     formfill("degree", "id_degree")
     formfill("semester", "id_semester")
  });
});
</script>

akademik/templates/forms/elements/formmap.html
<!-- Kawałek z klikalną mapą dla usera. Do dopracowania -->
<div class="card cardio">
<div class="card-body">
<img src="https://i0.wp.com/www.codexworld.com/wp-content/uploads/2015/12/add-google-map-to-website-marker-codexworld.png?resize=887%2C307&ssl=1" alt="Tu idzie mapa googla do zaznaczania pozycji jako input" class="img-fluid">
<br>
<br>
<p class="pref2">{{ formitem.click_map }} <button class="btn btn-light butt">{{ formitem.search }}</button></p>
<p class="fonteo"><b>{{ formitem.warning_f }}:</b> {{ formitem.check_search }}</p>
<p class="fonteo"><b>{{ formitem.warning_f }}2:</b> {{ formitem.check_mandatory }}</p>
<br>
</div>
</div>
<br>

akademik/templates/forms/elements/sh_preferences.html
<div class="card cardio">
<div class="maintitle">{{ formitem.preferences }}</div>
<div class="card-body">
<p class="pref"> {{ formitem.match_prefs }} <a href="#" class="badge badge-light">{{ formitem.see_map }}</a></p>
<p class="pref">
   1:
    <select {% if service %} required {% endif %} id="sh_choice1" class="form-control form-control-sm">
             <option value ="None" disabled="disabled" selected="selected">{{ formitem.list_select }}:</option>
           {% for item in houselist %}
              <option value ="{{ forloop.counter }}">{{ item }}</option>
           {% endfor %}
    </select>
   2:
    <select {% if service %} required {% endif %} id="sh_choice2" class="form-control form-control-sm">
             <option value ="None" disabled="disabled" selected="selected">{{ formitem.list_select }}:</option>
           {% for item in houselist %}
              <option value ="{{ forloop.counter }}">{{ item }}</option>
           {% endfor %}
    </select>
   3:
    <select {% if service %} required {% endif %} id="sh_choice3" class="form-control form-control-sm">
             <option value ="None" disabled="disabled" selected="selected">{{ formitem.list_select }}:</option>
           {% for item in houselist %}
              <option value ="{{ forloop.counter }}">{{ item }}</option>
           {% endfor %}
    </select>
</p>
<p class="pref">
    {{ formitem.i_ask }} :
    <select {% if service %} required {% endif %} id="if_room_change" class="form-control form-control-sm">
             <option value ="None" disabled="disabled" selected="selected">{{ formitem.list_select }}:</option>
           {% for item in staylist %}
              <option value ="{{ forloop.counter }}">{{ item }}</option>
           {% endfor %}
    </select>
</p>
<p class="pref">
    {{ formitem.time_in_sh }} :
    <select {% if service %} required {% endif %} id="duration" class="form-control form-control-sm">
             <option value ="None" disabled="disabled" selected="selected">{{ formitem.list_select }}:</option>
           {% for item in periodlist %}
              <option value ="{{ forloop.counter }}">{{ item }}</option>
           {% endfor %}
    </select>
</p>
</div>
</div>
<br>
<!--Ukryte pola formularza-->
{{ form.sh_choice1 }}{{ form.sh_choice2 }}{{ form.sh_choice3 }}
{{ form.duration }}{{ form.if_room_change }}
<!--Skrypt zapełniający pola-->
<script>
  $(document).ready(function()
  {
    $('#send').click(function()
   {
    formfill("sh_choice1", "id_sh_choice1")
    formfill("sh_choice2", "id_sh_choice2")
    formfill("sh_choice3", "id_sh_choice3")
    formfill("if_room_change", "id_if_room_change")
    formfill("duration", "id_duration")
  });
});
</script>

akademik/templates/forms/elements/userdata1.html
<!-- Wyświetla podstawowe aktualne dane usera. Do formularza i innych miejsc. -->
<div class="card cardio">
<div class="maintitle">{{ formitem.personal_data }}</div>
<div class="card-body">
<p class ="userdata"><b class="bolder">{{ formitem.name }}: </b> <b class="bolder2"> {{ udata.first_name }}  </b> <b class="bolder">{{ formitem.surname }}: </b><b class="bolder2"> {{ udata.last_name }}</b></p>
<p class ="userdata"><b class="bolder">{{ formitem.citizenship }}:  </b><b class="bolder2"> {{ udata.citizenship }}  </b>
<b class="bolder">{{ formitem.gender }}:  </b>
  {% if udata.gender == 0 %}
    <b class="bolder2">{{ formitem.other }}  <b>
 {% elif udata.gender == 1 %}
    <b class="bolder2">{{ formitem.male }}  </b>
 {% elif udata.gender == 2 %}
    <b class="bolder2">{{ formitem.female }}</b>
 {% endif %}
</p>
{% if udata.dowod %}
  <p class ="userdata"><b class="bolder">{{ formitem.dowod }}: </b> <b class="bolder2">{{ udata.dowod }}</b></p>
{% elif udata.passport %}
  <p class ="userdata"><b class="bolder">{{ formitem.passport }}: </b> <b class="bolder2">{{ udata.passport }}</b></p>
{% endif %}

<p class ="userdata"><b class="bolder">{{ formitem.defaul_t }} {{ formitem.email }}: </b><b class="bolder2"> {{ udata.email }} </b></p>
<p><b class="bolder">{{ formitem.defaul_t }} {{ formitem.telephone }}: </b>
{% if udata.telephone %}
  <b class="bolder2">{{ udata.telephone }}</b></p>
{% else %}
  <b class="bolder2">{{ formitem.tel_mandatory }}!! </b>
{% endif %}
<p class ="userdata"><b class="bolder">{{ formitem.warning_f }}: <a  class="bolder" href="https://core2.sspw.pl/login" target="blank">{{ formitem.data_correct }}</a></b></p>
</div>
</div>
<br>

akademik/templates/forms/elements/userdata2.html
<!-- Wyświetla dane adresowe usera - widoczne tylko w niektórych formularzach -->
<div class="card cardio">
<div class="maintitle">{{ formitem.adress_data }}</div>
<div class="card-body">
<p class="pref">
  <b>{{ formitem.street }}</b>: {{ udata.street }}
  <b>{{ formitem.building_no }}</b>: {{ udata.building_no }}
  {% if udata.local_no %}
   <b>{{ formitem.local_no }}</b>: {{ udata.local_no }}
  {% endif %}
</p>
<p class="pref">
  <b>{{ formitem.postcode }}</b>: {{ udata.postcode }}
  <b>{{ formitem.city }}</b>: {{ udata.city }}
</p>
<p class="bolder"><b>{{ formitem.warning_f }}:</b> <b><a href="https://core2.sspw.pl/login" target="blank" class="bolder">{{ formitem.data_correct }}</a></b></p>
</div>
</div>

<br>